import React from "react";
import { useNavigate } from "react-router-dom";
import s from "./BloomLog.module.css";
import img1 from "../images/Simulator Screenshot - iPhone 17 Pro - 2026-05-05 at 14.16.06.png";
import img2 from "../images/Simulator Screenshot - iPhone 17 Pro - 2026-05-05 at 14.23.50.png";

const stack = [
  "REACT NATIVE",
  "TYPESCRIPT",
  "OPENAI",
  "SUPABASE",
  "SQLITE",
  "EXPO",
];

const features = [
  {
    icon: "✦",
    title: "AI-Generated Prompts",
    desc: "Every day surfaces a fresh, thoughtful prompt powered by AI — designed to help you reflect without staring at a blank page.",
  },
  {
    icon: "◑",
    title: "Mood Tracking",
    desc: "Log your mood with each entry. Over time, BloomLog surfaces patterns — your happiest days, your calmest weeks — all visualised beautifully.",
  },
  {
    icon: "◈",
    title: "Streak System",
    desc: "A quiet streak counter that rewards consistency. Write every day and watch your streak grow — no pressure, just gentle momentum.",
  },
  {
    icon: "⬡",
    title: "Offline First",
    desc: "Built on SQLite, every entry is saved locally first. No connection? No problem. Your journal is always available, always private.",
  },
  {
    icon: "↑",
    title: "Supabase Sync",
    desc: "When you're online, entries sync silently to Supabase. Your diary is backed up forever — safe, encrypted, and yours alone.",
  },
  {
    icon: "◎",
    title: "Insights Dashboard",
    desc: "A visual breakdown of mood timelines, top emotions, and weekly reflections — so your writing becomes something you can learn from.",
  },
];

const whyTheseTools = [
  {
    tech: "React Native + Expo",
    why: "Single codebase for iOS and Android. Expo's managed workflow meant faster iteration without native build headaches.",
  },
  {
    tech: "TypeScript",
    why: "End-to-end type safety across components, Supabase queries, and SQLite schemas caught bugs before they ever hit production.",
  },
  {
    tech: "SQLite (offline first)",
    why: "Local persistence ensures the app works without internet. SQLite is battle-tested, fast, and fits perfectly in a mobile context.",
  },
  {
    tech: "Supabase Authentication",
    why: "Handled user Login and Signup via Auth Table, which is handled by postgres service.",
  },
  {
    tech: "Supabase Database - Postgres and SQLite",
why: "Handled auth, real-time sync, and row-level security out of the box. Replaced what would have been weeks of backend work.",
  },
  {
    tech: "Supabase Cloud (and Buckets)",
        why: "Created buckets for Images and Audio storage, for storing compressed files upto 1MB for each journal entry. Managed entries and prompts tables.",
  },
];
export default function BloomLog() {
  // const [videoPlaying, setVideoPlaying] = useState(false);
  const navigate = useNavigate();
  const onBack = () => navigate("/");

  React.useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className={s.page}>
      {/* ── Back nav ── */}
      <button className={s.back} onClick={onBack}>
        ← Back to portfolio
      </button>

      {/* ── Hero ── */}
      <section className={s.hero}>
        <div className={s.heroInner}>
          <div className={s.heroLeft}>
            <p className={s.eyebrow}>03 — SELECTED WORK</p>
            <h1 className={s.title}>BloomLog</h1>
            <p className={s.subtitle}>Journal App</p>
            <p className={s.desc}>
              A journal app with plenty of prompts generated by AI, intended to
              declutter the mind and encourage daily reflection. A private daily
              journal where you write, track your mood, and watch your streak
              grow. AI provides weekly insights over a pattern of your entries.
              Features Offline Storage as well as Supabase server syncing for
              saving the diary forever.
            </p>
            <div className={s.stackRow}>
              {stack.map((t) => (
                <span key={t} className={s.stackTag}>
                  {t}
                </span>
              ))}
            </div>
            <div className={s.heroActions}>
              {/* <a
                href="https://drive.google.com/drive/folders/161EGYD_avY5AxqTZ_3A7Mi9SNsPBpyIX?usp=sharing"
                className={s.btnPrimary}

              >
                WATCH DEMO ↗
              </a>
            <a href="#" className={s.btnGhost}>
                APP STORE ↗
              </a>
              <a href="#" className={s.btnGhost}>
                PLAY STORE ↗
              </a> */}
            </div>
          </div>

          {/* Phone mockups from screenshot feel */}
          <div className={s.heroRight}>
            <div className={s.mockupsWrap}>
              <div className={s.glowBg} />

              {img1 ? (
                <img
                  src={img1}
                  alt="BloomLog screenshot 1"
                  className={s.projectImg}
                />
              ) : null}

              {img2 ? (
                <img
                  src={img2}
                  alt="BloomLog screenshot 2"
                  className={s.projectImg}
                />
              ) : null}
            </div>
          </div>
        </div>
      </section>

      {/* ── Features ── */}
      <section className={s.featuresSection}>
        <div className={s.sectionInner}>
          <p className={s.sectionEyebrow}>WHAT IT DOES</p>
          <h2 className={s.sectionHeading}>
            Built for the way
            <br />
            people actually reflect.
          </h2>
          <div className={s.featuresGrid}>
            {features.map((f, i) => (
              <div key={i} className={s.featureCard}>
                <span className={s.featureIcon}>{f.icon}</span>
                <h3 className={s.featureTitle}>{f.title}</h3>
                <p className={s.featureDesc}>{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Demo Video ── */}
      {/* <section className={s.demoSection} id="demo">
        <div className={s.sectionInner}>
          <p className={s.sectionEyebrow}>SEE IT IN ACTION</p>
          <h2 className={s.sectionHeading}>Demo</h2>
          <div className={s.videoWrap}>
            {!videoPlaying ? (
              <div
                className={s.videoThumb}
                onClick={() => setVideoPlaying(true)}
              >
                {/* Decorative placeholder until real video URL is added 
                <div className={s.videoGlow} />
                <div className={s.videoPhonePreview}>
                  <div className={s.vpBar}>
                    <div className={s.vpIsland} />
                  </div>
                  <div className={s.vpContent}>
                    <p className={s.vpGreeting}>Good afternoon,</p>
                    <p className={s.vpName}>Rasleen</p>
                    <div className={s.vpStreak}>12 day streak 🌿</div>
                  </div>
                </div>
                <button className={s.playBtn} aria-label="Play demo video">
                  <svg
                    viewBox="0 0 24 24"
                    fill="currentColor"
                    width="28"
                    height="28"
                  >
                    <path d="M8 5v14l11-7z" />
                  </svg>
                </button>
                <p className={s.videoHint}>Click to play demo</p>
              </div>
            ) : (
              // Replace the src below with your actual YouTube embed or video URL
              <iframe
                className={s.videoIframe}
                src="https://www.youtube.com/watch?v=SEw8IsSXRSU&list=RDSEw8IsSXRSU&start_radio=1"
                title="BloomLog Demo"
                allow="autoplay; encrypted-media"
                allowFullScreen
              />
            )}
          </div>
        </div>
      </section> */}

      {/* ── Tech Stack deep dive ── */}
      <section className={s.techSection}>
        <div className={s.sectionInner}>
          <p className={s.sectionEyebrow}>TECHNICAL DECISIONS</p>
          <h2 className={s.sectionHeading}>Why these tools.</h2>
          <div className={s.techGrid}>
            {whyTheseTools.map((item, i) => (
              <div key={i} className={s.techCard}>
                <h3 className={s.techName}>{item.tech}</h3>
                <p className={s.techWhy}>{item.why}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Bottom CTA ── */}
      <section className={s.ctaSection}>
        <div className={s.sectionInner}>
          <h2 className={s.ctaHeading}>Try BloomLog.</h2>
          <p className={s.ctaDesc}>
            Available soon on iOS and Android. Free to download, private by
            design.
          </p>
          <div className={s.ctaActions}>
            {/* <a href="#" className={s.btnPrimary}>
              APP STORE ↗
            </a>
            <a href="#" className={s.btnPrimary}>
              PLAY STORE ↗
            </a> */}
            <button className={s.btnGhost} onClick={onBack}>
              ← Back to portfolio
            </button>
          </div>
        </div>
      </section>
    </div>
  );
}
