import React, { useState } from 'react';
import s from './Projects.module.css';
import img1 from '../images/Simulator Screenshot - iPhone 17 Pro - 2026-05-05 at 14.16.06.png';
import img2 from '../images/Simulator Screenshot - iPhone 17 Pro - 2026-05-05 at 14.23.50.png';
import img3 from '../images/AiInsight1.png';
import img4 from '../images/AiInsight2.png';


const projects = [
  {
    num: '001',
    label: 'FEATURED PROJECT',
    title: 'BloomLog - Journal App',
    desc: 'A journal app with plenty of prompts generated by AI, intended to decluttering and mind relaxation. A private daily journal where you write, track your mood, and watch your streak grow. Features Offline Storage as well as Supabase server syncing for saving the diary forever.',
    stack: ['REACT NATIVE', 'TYPESCRIPT', 'SUPABASE', 'SQLITE', 'EXPO'],//'CLAUDE AI','LOVABLE AI'
    aiCompanions : ['Claude','Lovable'],
    gradient: 'linear-gradient(135deg, #a78bfa, #60a5fa, #34d399)',
    links: [{ label: 'READ MORE ↗', href: '#' }],//{ label: 'PLAY STORE ↗', href: '#' }
  },
  // {
  //   num: '002',
  //   label: 'OPEN SOURCE',
  //   title: 'Forge UI',
  //   desc: 'A headless, accessible React component library with 40+ components. Zero dependencies, full TypeScript support, and a flexible theming API built for design systems.',
  //   stack: ['REACT', 'TYPESCRIPT', 'STORYBOOK', 'VITEST', 'ROLLUP'],
  //   gradient: 'linear-gradient(135deg, #f9a8d4, #fb923c, #fbbf24)',
  //   links: [{ label: 'NPM ↗', href: '#' }, { label: 'GITHUB ↗', href: '#' }],
  // },
  // {
  //   num: '003',
  //   label: 'CHROME EXTENSION',
  //   title: 'Perf Lens',
  //   desc: 'A DevTools extension surfacing Core Web Vitals in real-time with actionable fix suggestions. Helps frontend teams ship faster pages without leaving the browser.',
  //   stack: ['VUE 3', 'VITE', 'CHROME API', 'TYPESCRIPT'],
  //   gradient: 'linear-gradient(135deg, #2dd4bf, #6366f1, #e879f9)',
  //   links: [{ label: 'CHROME STORE ↗', href: '#' }, { label: 'DOCS ↗', href: '#' }],
  // },
];

export default function Projects() {
  const [active, setActive] = useState(0);
  const project = projects[active];

  return (
    <section className={s.section} id="projects">
      <div className={s.inner}>
        <div className={s.header}>
          <div>
            <span className={`${s.sectionTag} reveal`}>03 — SELECTED WORK</span>
            <h2 className={`${s.heading} reveal d1`}>Projects</h2>
          </div>
          {/* <span className={`${s.counter} reveal d1`}>
            {String(active + 1).padStart(3, '0')} / {String(projects.length).padStart(3, '0')}
          </span> */}
        </div>

        <div className={s.layout}>
          {/* Left: project images */}
          <div className={`${s.visual} reveal d2`}>
            <div className={s.imageGrid}>
              <img src={img1} alt="BloomLog screenshot 1" className={s.projectImg} />
              <img src={img2} alt="BloomLog screenshot 2" className={s.projectImg} />
              <div className={s.imageColumn}>
                <img src={img3} alt="BloomLog screenshot 3" className={s.projectImgSmall} />
                <img src={img4} alt="BloomLog screenshot 4" className={s.projectImgSmall} />
              </div>
            </div>
          </div>

          {/* Right: info */}
          <div className={`${s.info} reveal d3`}>
            <p className={s.infoLabel}>{project.label}</p>
            <h3 className={s.infoTitle}>{project.title}</h3>
            <p className={s.infoDesc}>{project.desc}</p>
            <div className={s.stack}>
              {project.stack.map(t => (
                <span key={t} className={s.stackTag}>{t}</span>
              ))}
            </div>
            {/* <div className={s.stack}>
              <p className={s.infoDesc}>AI Companions:</p>
              {project.aiCompanions.map(t => (
                <span key={t} className={s.stackTag}>{t}</span>
              ))}
            </div> */}
              
            <div className={s.infoActions}>
              {project.links.map(l => (
                <a key={l.label} href={l.href} className={l.label.includes('LIVE') || l.label.includes('NPM') || l.label.includes('CHROME') ? s.btnPrimary : s.btnGhost}>
                  {l.label}
                </a>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
